$schema: "1.0"
name: "tjs-eng"
image: acgdevbox/vscodeImageDef@1.0.0
description: "This definition is my custom image"

tasks:
  - name: ~/winget
    description: Install AZD
    parameters:
      package:  Microsoft.Azd

  - name: ~/winget
    description: Install Visual Studio Code
    parameters:
      package:  Microsoft.VisualStudioCode

  - name: ~/powershell
    parameters:
      command: |
        $env:Path = [System.Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('Path','User') 
